@url = http://localhost:8080

// @name register
POST {{url}}/user/register
content-type: application/json

{
    "user": {
        "username": "Shubham",
        "email": "shubham@email.com",
        "password": "password"
    }
}

###
# @name login
POST {{url}}/user/login
content-type: application/json

{
    "user": {
        "email": "shubham@email.com",
        "password": "password"
    }
}

###
# @name profile
GET {{url}}/user/profile
content-type: application/json
Authorization: Bearer {{login.response.body.$.token}}

###
# @name showAllUsers
GET {{url}}/user/all
content-type: application/json
Authorization: Bearer {{login.response.body.$.token}}
