@url = http://localhost:8080/api/v1

// @name register
POST {{url}}/auth/register
content-type: application/json

{
    "username": "Shubham",
    "email": "shubham@email.com",
    "password": "password"
}

###
// @name verify
GET {{url}}/auth/verify/{{register.response.body.$.verificationId}}
content-type: application/json

###
# @name login
POST {{url}}/auth/login
content-type: application/json

{
    "email": "shubham@email.com",
    "password": "password"
}

###
# @name profile
GET {{url}}/auth/profile
content-type: application/json
Authorization: Bearer {{login.response.body.$.token}}


###
# @name showUsers
GET {{url}}/users
content-type: application/json
Authorization: Bearer {{login.response.body.$.token}}

###
# @name showOneUser
GET {{url}}/users/{{showUsers.response.body.data[0].id}}
content-type: application/json
Authorization: Bearer {{login.response.body.$.token}}
